import { Project } from "@/types";

export const roProjects: Project[] = [
  {
    id: "pfcrm",
    title: "PFCRM",
    tag: "Instrument Enterprise",
    shortDescription: "Un CRM personalizat care gestionează vânzări de volum mare cu integrare scraping, telefonie și semnătură electronică.",
    description: "Un CRM complet construit pentru o operațiune de vânzări de volum mare. Am înlocuit foile de calcul fragmentate și procesele manuale cu un sistem inteligent și automatizat.",
    techStack: ["React", "Node.js", "Puppeteer", "DocuSign API", "RingCentral API", "PostgreSQL"],
    visual: "https://picsum.photos/seed/pfcrm/1200/800",
    status: "În Producție",
    gridSize: "large",
    featured: true,
    liveUrl: "https://pfcrm.example.com",
    situation: "Clientul se îneca în introducerea manuală a datelor. Echipa de vânzări petrecea peste 4 ore zilnic cu introducerea datelor în foi de calcul, sisteme CRM și fișiere text. Lead-uri pierdute, duplicate și follow-up-uri omise costau aproximativ 15.000$/lună în venituri pierdute.",
    task: "Construiește un CRM unificat care captează automat lead-urile din multiple surse, se integrează cu sistemul de telefonie pentru log-area apelilor și automatizează fluxurile de lucru pentru documente.",
    action: "Am construit o aplicație custom React/Node.js cu Puppeteer pentru scraping în timp real din multiple canale. Am integrat RingCentral API pentru log-area și înregistrarea automată a apelilor. Am creat integrare DocuSign pentru semnarea seamless a contractelor. Toate datele se sincronizează în PostgreSQL cu deduplicare inteligentă.",
    result: "Am redus introducerea manuală a datelor cu 95%. Echipa de vânzări se concentrează acum pe vânzări în loc de muncă de birou. Log-area apelilor este automată, iar timpul pentru contracte a scăzut de la 48 de ore la sub 2 ore. Clientul raportează o creștere de 20% în oferte închise în prima lună."
  },
  {
    id: "chef",
    title: "Chef De Chef",
    tag: "Sistem de Rezervări",
    shortDescription: "Sistem end-to-end de rezervări și management clienți pentru o afacere de cursuri de dans.",
    description: "Platformă completă de booking și management clienți pentru o companie de instruire în dans. Am simplificat întregul flux de lucru pentru rezervări.",
    techStack: ["Next.js", "Resend", "Stripe", "Prisma", "PostgreSQL"],
    visual: "https://picsum.photos/seed/chef/800/1000",
    status: "Live",
    gridSize: "medium",
    featured: false,
    liveUrl: "https://chefdechef.example.com",
    situation: "O companie de instruire în dans gestiona booking-urile prin Google Forms și mesaje manuale WhatsApp. Dubla-programarea era frecventă, urmărirea plăților era un coșmar, iar clienții își pierdeau frecvent sesiunile.",
    task: "Creează un portal self-service de booking cu mementouri automate, plăți integrate și un dashboard admin pentru management-ul personalului.",
    action: "Am construit o aplicație Next.js cu o interfăță frumoasă de calendar pentru booking. Am integrat Stripe pentru plăți sigure cu generare automată de facturi. Am folosit Resend pentru confirmări prin email și mementouri tip SMS. Am creat un dashboard admin cuprinzător cu analize.",
    result: "Am eliminat complet dubla-programarea. Rata de colectare a plăților a crescut de la 70% la 98%. Absentele au scăzut cu 80% datorită mementourilor automate. Personalul petrece acum minute în loc de ore cu administrarea."
  },
  {
    id: "faresnap",
    title: "FareSnap",
    tag: "Extensie Browser",
    shortDescription: "Extensie Chrome pentru agenții de travel pentru a captura și compara rapid opțiunile de bilete de avion.",
    description: "Un instrument de productivitate care îi ajută pe agenții de travel să captureze, organizeze și compare opțiunile de bilete din multiple surse.",
    techStack: ["React", "Chrome Extension API", "Manifest V3", "Local Storage"],
    visual: "https://picsum.photos/seed/faresnap/600/400",
    status: "Live",
    featured: false,
    gridSize: "small",
    liveUrl: "https://chrome.google.com/webstore/detail/faresnap",
    situation: "Agenții de travel comută constant între site-uri web de airline, instrumente de comparare bilete și notițele proprii. Capturarea biletelor pentru propuneri este repetitivă și predispusă la erori.",
    task: "Creează o extensie Chrome care le permite agenților să captureze biletele cu un click, să le organizeze în foldere și să exporte pentru propuneri.",
    action: "Am construit o extensie Manifest V3 cu o interfață elegantă popup. Am implementat capturare cu un click din orice website. Am creat organizare în foldere cu căutare și filtrare. Am adăugat export în PDF și integrare email.",
    result: "Peste 100 de utilizatori activi săptămânal. Agenții raportează economisirea a peste 1 oră zilnic cu research-ul de bilete. Rating de 4.8 stele cu mărturii despre economie de timp."
  },
  {
    id: "meta",
    title: "Meta Graph Automator",
    tag: "Instrument Automatizare",
    shortDescription: "Organizare inbox folosind Meta Graph API pentru sortarea și categorisirea automată a mesajelor.",
    description: "Automatizare inteligentă a inbox-ului care folosește Meta Graph API pentru a categorisi, sorta și prioritiza mesajele primite.",
    techStack: ["Python", "FastAPI", "Meta Graph API", "PostgreSQL"],
    visual: "https://picsum.photos/seed/meta/800/600",
    status: "Live",
    featured: false,
    gridSize: "small",
    liveUrl: "https://meta-automator.example.com",
    situation: "O agenție de marketing primește peste 500 de mesaje zilnic din inbox-ul Meta pe multiple conturi. Categorisirea manuală între mesaje urgente și non-urgente era copleșitoare și ducea la întârzieri în răspunsuri pentru lead-uri importante.",
    task: "Construiește o automatizare care sortează mesajele primite după urgență și categorie, marcând lead-urile prioritare pentru atenție imediată.",
    action: "Am dezvoltat un serviciu Python folosind Meta Graph API pentru streaming în timp real al mesajelor. Am creat reguli de clasificare bazate pe ML din conținutul mesajelor și comportamentul expeditorului. Am construit un sistem de coadă de priorități cu webhooks pentru notificări instant.",
    result: "Timpul de răspuns pentru lead-uri critice a scăzut de la 4 ore la sub 15 minute. Productivitatea echipei a crescut prin eliminarea triajului manual. Agenția raportează o creștere de 20.000$/lună în lead-uri captate."
  },
  {
    id: "cabin",
    title: "CabinStory",
    tag: "SaaS Travel Tech",
    shortDescription: "Instrument de prezentare care ajută agenții de travel să creeze itinerarii impresionante și profesionale în minute.",
    description: "O platformă SaaS care împuternicește agenții de travel să creeze itinerarii de travel frumoase și profesionale. \"Canva pentru agenții de travel.\"",
    techStack: ["React", "PostgreSQL", "AWS S3", "PDF Generation", "Stripe"],
    visual: "https://picsum.photos/seed/cabin/1200/600",
    status: "Beta Live",
    gridSize: "medium",
    featured: true,
    liveUrl: "https://cabinstory.com",
    situation: "Agenții de travel petrec 2-3 ore per itinerariu folosind instrumente pe care nu le cunosc (Canva, PowerPoint). Rezultatul este inconsitent, prezentări neprofesionale care nu închid oferte.",
    task: "Construiește un instrument specializat care le permite agenților să creeze itinerarii în sub 10 minute, cu drag-and-drop și șabloane frumoase.",
    action: "Am proiectat un editor bazat pe componente cu blocuri de itinerarii drag-and-drop. Am creat peste 50 de șabloane profesionale pentru diferite tipuri de călătorii. Am integrat export PDF pentru livrare către clienți. Am adăugat funcții de colaborare pentru fluxuri de lucru în echipă.",
    result: "Agenții creează acum itinerarii în 5-10 minute în loc de 2-3 ore. Calitatea prezentărilor către clienți s-a îmbunătățit dramatic. Beta timpurie arată conversii cu 40% mai rapide."
  },
  {
    id: "gds",
    title: "GDS Micro-Tools",
    tag: "Utilitare Interne",
    shortDescription: "Colecție de instrumente de productivitate pentru profesioniștii din industria travel.",
    description: "O suită de micro-instrumente specializate care rezolvă probleme specifice pentru profesioniștii din industria travel.",
    techStack: ["TypeScript", "SVG", "React"],
    visual: "https://picsum.photos/seed/gds/800/400",
    status: "Live",
    featured: false,
    gridSize: "small",
    liveUrl: "https://gds-tools.example.com",
    situation: "Agenții de travel au nevoie constant de instrumente simple care nu există în altă parte - generatoare aleatoare de nume pentru training, vizualizatoare hărți de scaune, convertoare de fus orar și altele. Apelează la căutări Google și instrumente online mediocre.",
    task: "Construiește o colecție de micro-instrumente focalizate, frumoase, proiectate specific pentru fluxurile de lucru din industria travel.",
    action: "Am creat peste 10 instrumente specializate inclusiv Generator de Nume, Vizualizator Hartă Scaune, Maestrul Fus Orar și altele. Fiecare instrument este proiectat cu cazuri de utilizare specifice industriei travel. Rapid, focalizat, fără înregistrare necesară.",
    result: "Folosit de sute de agenți zilnic. Instrumente apar pe prima pagină Google pentru căutări specifice industriei. A devenit un canal de generare de lead-uri pentru business-ul mai larg."
  }
];
